<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ra3.BattleNet.Updater.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ra3.BattleNet.Updater.Share\Ra3.BattleNet.Updater.Share.csproj" />
  </ItemGroup>

</Project>
