<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ra3.BattleNet.Updater.Client\Ra3.BattleNet.Updater.Client.csproj" />
    <ProjectReference Include="..\Ra3.BattleNet.Updater.Share\Ra3.BattleNet.Updater.Share.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Ra3.BattleNet.Updater.Share\hdiffpatch_bin\win-x86\hdiffz.exe"
             Link="hdiffpatch_bin\win-x86\hdiffz.exe"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\Ra3.BattleNet.Updater.Share\hdiffpatch_bin\win-x86\hpatchz.exe"
             Link="hdiffpatch_bin\win-x86\hpatchz.exe"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
