// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ra3.BattleNet.Updater.Server.PatchIndexGenerator;

#nullable disable

namespace Ra3.BattleNet.Updater.Server.PatchIndexGenerator.Migrations
{
    [DbContext(typeof(UpdaterContext))]
    [Migration("20250725155032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Ra3.BattleNet.Updater.Server.PatchIndexGenerator.EFCoreModels.PatchIndexModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("BuildVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("FileGuid")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.Property<byte>("MajorVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MinorVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("NewContentHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("OldContentHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PatchName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("PatchIndexes");
                });
#pragma warning restore 612, 618
        }
    }
}
